[[redirects]]
  # Redirect /recliner/* requests to the recliner folder
  from = "/recliner/*"
  to = "/figurative-labs-app/recliner/:splat"
  status = 200

[[redirects]]
  # Redirect /swiss_army_knife/* requests to the swiss_army_knife folder
  from = "/swiss_army_knife/*"
  to = "/figurative-labs-app/swiss_army_knife/:splat"
  status = 200
